mqtt:
  api_url: http://mqtt-bridge-dev:5003
  topics:
    grid_power: inverter_1/grid_power/state
    pv_power: inverter_1/pv_power/state
    battery_power: total/battery_power/state
    load_power: inverter_1/load_power/state
storage:
  raw_path: /app/data/raw/
  aggregated_path: /app/data/aggregated/
  results_path: /app/data/results.json
simulation:
  timezone: Europe/London
  interval_minutes: 30
  history_range: 700d
  history_window: 1m
  baseline_tariff_id: flat_standard
tariffs:
- id: flat_standard
  name: EON Next Drive v6
  type: day_night
  standing_charge: 56.89
  export_rate: 16.5
  day:
    rate: 21.8
    start: 07:00
    end: 00:00
  night:
    rate: 6.7
    start: 00:00
    end: 07:00
- id: economy7
  name: EON Next Drive v21
  type: day_night
  standing_charge: 60.0
  export_rate: 9.0
  day:
    rate: 28.44
    start: 06:00
    end: 00:00
  night:
    rate: 9.0
    start: 00:00
    end: 06:00
- id: british_gas
  name: British Gas
  type: flat
  standing_charge: 48.537
  export_rate: 0.0
  import_rate: 24.385
